// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppCar1.Models;

namespace WebAppCar1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220601104442_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("WebAppCar1.Models.Car", b =>
                {
                    b.Property<int>("car_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("car_ImageUrl")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("car_Name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("car_Plate")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("person_ID")
                        .HasColumnType("int");

                    b.HasKey("car_ID");

                    b.ToTable("car");
                });

            modelBuilder.Entity("WebAppCar1.Models.Person", b =>
                {
                    b.Property<int>("person_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("person_FName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("person_LName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("person_Phone")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("person_ID");

                    b.ToTable("person");
                });
#pragma warning restore 612, 618
        }
    }
}
